version: '3.8'
services:
    dmit_mysql_db:
        image: mysql:8.0
        container_name: dmit_mysql_db
        restart: always
        environment:
            - MYSQL_DATABASE=dmit-api
            - MYSQL_UESR=root
            - MYSQL_PASSWORD=311034
            - MYSQL_ROOT_PASSWORD=311034
            - MYSQL_HOST=mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - dmit-net

    #dmit_nginx:
    #    build:
    #        context: .
    #        dockerfile: Dockerfile.nginx
    #    image: nginx:latest
    #    container_name: dmit_nginx
    #    volumes:
    #        - ./nginx:/etc/nginx
    #        - ./certs:/etc/nginx/certs
    #        - ./ssl-certificates:/etc/letsencrypt
    #        - ./ssl-certificates-api:/etc/letsencrypt-api
    #    ports:
    #        - 80:80
    #        - 443:443
    #    depends_on:
    #        - dmit_php
    #    networks:
    #        - dmit-net

    dmit_php:
        build:
            context: .
            dockerfile: Dockerfile.production
        container_name: dmit_php
        working_dir: /var/www/html
        volumes:
            - ./dmit-back:/var/www/html/dmit-back
            - ./dmit-front:/var/www/html/dmit-front
            - ./dmit-afip-certificates:/usr/afip-certificates
        ports:
            - 3331:3331
        depends_on:
            - dmit_mysql_db
        networks:
            - dmit-net

networks:
    dmit-net:


