version: '3.8'

services:
    dmit_mysql_db:
        image: mysql:8.0
        container_name: dmit_mysql_db
        restart: always
        environment:
            - MYSQL_DATABASE=dmit-api
            - MYSQL_UESR=root
            - MYSQL_PASSWORD=311034
            - MYSQL_ROOT_PASSWORD=311034
            - MYSQL_HOST=mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - dmit_network

    dmit_api_nginx:
        image: nginx:alpine
        container_name: dmit_api_nginx
        ports:
            - 7000:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./dmit-back:/var/www/html
        depends_on:
            - dmit_api_php
        networks:
            - dmit_network

    dmit_api_php:
        build:
            context: .
            dockerfile: Dockerfile.production
        container_name: dmit_api_php
        volumes:
            - ./dmit-back:/var/www/html
        depends_on:
            - dmit_mysql_db
        networks:
            - dmit_network

networks:
    dmit_network:
        external: true
