version: '3.8'

services:
    poste:
        image: analogic/poste.io
        container_name: dmit_mail
        hostname: mail.dmit.ar
        restart: always
        network_mode: "host"
        volumes:
            - maildata:/data
            - maillogs:/var/log
            - ./ssl-certificates:/etc/ssl/certs
        environment:
            - HTTPS=ON
            - SSL_CERT=/etc/ssl/certs/fullchain.pem
            - SSL_KEY=/etc/ssl/private/privkey.pem

volumes:
    maildata:
    maillogs:
