version: '3.8'
services:
    dmit_mysql_db:
        image: mysql:8.0
        container_name: dmit_mysql_db
        restart: always
        environment:
            - MYSQL_DATABASE=dmit-api
            - MYSQL_UESR=root
            - MYSQL_PASSWORD=311034
            - MYSQL_ROOT_PASSWORD=311034
            - MYSQL_HOST=mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - dmit-net

    dmit_php:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: dmit_php
        working_dir: /var/www
        volumes:
            - ./src:/var/www/html
            - ./../packages:/usr/packages
        ports:
            - 8001:80
        depends_on:
            - dmit_mysql_db
        networks:
            - dmit-net

networks:
    dmit-net:


