version: '3.8'

services:
    poste:
        image: analogic/poste.io
        container_name: dmit_mail
        hostname: mail.dmit.ar
        restart: always
        network_mode: "host"
        ports:
            - "25:25"
            - "8080:80"
            - "8443:443"
            - "110:110"
            - "143:143"
            - "993:993"
            - "995:995"
            - "4190:4190"
        volumes:
            - maildata:/data
            - maillogs:/var/log
            - ./ssl-certificates:/etc/ssl/certs
        environment:
            - HTTPS=ON
            - SSL_CERT=/etc/ssl/certs/fullchain.pem
            - SSL_KEY=/etc/ssl/private/privkey.pem
        networks:
            - dmit-net

volumes:
    maildata:
    maillogs:


networks:
    dmit-net:
